### ISSUE TITLE
latest doesn't accept any voucher

### ISSUE THREAD

**Issue by cryptolovi** [kpeiruza/docker-hashtopolis-server#2]
playing a bit around with your hashtopolis docker server, but the stable version I have no problems connecting new agents with a voucher. The latest version just doesn't except any voucher.

When using a non existent voucher I get the correct answer from the hashtopolis server;
Registering failed: {'action': 'register', 'response': 'ERROR', 'message': 'Provided voucher does not exist.'}

But with a voucher that does exists;
No token found! Please enter a voucher to register your agent:
floating
{'action': 'register', 'voucher': 'floating', 'name': 'some_host_name'}
Resetting dropped connection: hashtopolis-server
http://hashtopolis-server:80 "POST /api/server.php HTTP/1.1" 500 0
Status code from server: 500
Request failed!

Even with the setting on that voucher doesn't expire. Might be related to the resetting dropped connection, but odd that I only get that on a good voucher  (agent is ubuntu 18,04). Also I have not setup the latest version of hashtopolis outside docker, so it might be related not to your docker project.

**Comment by kpeiruza** [comment]
The image pulled the code of Hashtopolis at the moment it got built. I've just triggered a new build (if everyting goes ok, it's going to be ready in about 15 min.)

Dunno if the error was caused by a bug in that release or maybe a missing library or directory permission. 

Please, docker pull & try again, if you bump into the same error, please, attach the docker logs so I don't need to bring up a lab to check it. 

Thanks!

**Comment by cryptolovi** [comment]
Did a pull and still the same. 

stable docker compose, sql tail log. 
```
2020-04-02T09:07:23.022730Z 0 [Note] Event Scheduler: Loaded 0 events
2020-04-02T09:07:23.022901Z 0 [Note] mysqld: ready for connections.
Version: '5.7.29'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```
stable docker hashtopolis log, after correct voucher (you see agent downloading 7zr)
```
xx - - [02/Apr/2020:09:11:36 +0000] "POST /api/server.php HTTP/1.1" 200 369 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "POST /api/server.php HTTP/1.1" 200 356 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "POST /api/server.php HTTP/1.1" 200 359 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "POST /api/server.php HTTP/1.1" 200 372 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "POST /api/server.php HTTP/1.1" 200 410 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "HEAD /static/7zr.bin HTTP/1.1" 200 304 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "GET /static/7zr.bin HTTP/1.1" 200 268192 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "POST /api/server.php HTTP/1.1" 200 367 "-" "s3-python-0.5.0"
xx - - [02/Apr/2020:09:11:36 +0000] "POST /api/server.php HTTP/1.1" 200 399 "-" "s3-python-0.5.0"

```

latest docker compose, hashtopolis server
```
Failed connecting to the database.... Sleeping 5s and retrying 11 more.
Failed connecting to the database.... Sleeping 5s and retrying 10 more.
Failed connecting to the database.... Sleeping 5s and retrying 9 more.
Setup finished, pruning /install folder
xx - - [02/Apr/2020:09:30:44 +0000] "GET / HTTP/1.1" 200 2482 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
xx - - [02/Apr/2020:09:30:44 +0000] "GET /static/bootstrap.min.css HTTP/1.1" 200 21425 "http://localhost:8888/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
xx - - [02/Apr/2020:09:30:50 +0000] "POST /login.php HTTP/1.1" 302 486 "http://localhost:8888/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
xx - - [02/Apr/2020:09:30:51 +0000] "GET /index.php HTTP/1.1" 200 3035 "http://localhost:8888/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
xx - - [02/Apr/2020:09:30:57 +0000] "GET /agents.php?new=true HTTP/1.1" 200 3527 "http://localhost:8888/index.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
xx - - [02/Apr/2020:09:31:02 +0000] "POST /agents.php?new=true HTTP/1.1" 302 497 "http://localhost:8888/agents.php?new=true" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
xx - - [02/Apr/2020:09:31:02 +0000] "GET /agents.php?new=true HTTP/1.1" 200 3676 "http://localhost:8888/agents.php?new=true" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0"
xx - - [02/Apr/2020:09:32:38 +0000] "POST /api/server.php HTTP/1.1" 500 345 "-" "s3-python-0.6.0"
```

Last line is the agent connecting with made correct voucher, with status code 500. Sql logs are the same.
If the server hasn't ticked the options vouchers can be used multiple times, the voucher get's used up. So the agent is pushing the correct voucher. With a tcp dump I also see the voucher, the server respond though;
```
	0x0030:  d9ee f4f0 4854 5450 2f31 2e30 2035 3030  ....HTTP/1.0.500
	0x0040:  2049 6e74 6572 6e61 6c20 5365 7276 6572  .Internal.Server
	0x0050:  2045 7272 6f72 0d0a 4461 7465 3a20 5468  .Error..Date:.Th
	0x0060:  752c 2030 3220 4170 7220 3230 3230 2030  u,.02.Apr.2020.0
	0x0070:  393a 3435 3a31 3820 474d 540d 0a53 6572  9:45:18.GMT..Ser
	0x0080:  7665 723a 2041 7061 6368 652f 322e 342e  ver:.Apache/2.4.
	0x0090:  3239 2028 5562 756e 7475 290d 0a45 7870  29.(Ubuntu)..Exp
	0x00a0:  6972 6573 3a20 5468 752c 2031 3920 4e6f  ires:.Thu,.19.No
	0x00b0:  7620 3139 3831 2030 383a 3532 3a30 3020  v.1981.08:52:00.
	0x00c0:  474d 540d 0a43 6163 6865 2d43 6f6e 7472  GMT..Cache-Contr
	0x00d0:  6f6c 3a20 6e6f 2d73 746f 7265 2c20 6e6f  ol:.no-store,.no
	0x00e0:  2d63 6163 6865 2c20 6d75 7374 2d72 6576  -cache,.must-rev
	0x00f0:  616c 6964 6174 650d 0a50 7261 676d 613a  alidate..Pragma:
	0x0100:  206e 6f2d 6361 6368 650d 0a43 6f6e 7465  .no-cache..Conte
	0x0110:  6e74 2d4c 656e 6774 683a 2030 0d0a 436f  nt-Length:.0..Co
	0x0120:  6e6e 6563 7469 6f6e 3a20 636c 6f73 650d  nnection:.close.
	0x0130:  0a43 6f6e 7465 6e74 2d54 7970 653a 2061  .Content-Type:.a
	0x0140:  7070 6c69 6361 7469 6f6e 2f6a 736f 6e0d  pplication/json.
	0x0150:  0a0d 0a                                  ...

```
Apache error log
```
Thu Apr 02 09:29:07.546316 2020] [core:notice] [pid 23] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
[Thu Apr 02 09:32:38.182720 2020] [php7:warn] [pid 28] [client xx] PHP Warning:  fopen(/var/www/html/inc/utils/locks/log.lock): failed to open stream: Permission denied in /var/www/html/inc/ut
ils/Lock.class.php on line 17
[Thu Apr 02 09:32:38.182755 2020] [php7:error] [pid 28] [client xx] PHP Fatal error:  Uncaught Exception: Could not open lockfile '/var/www/html/inc/utils/locks/log.lock'! in /var/www/html/inc
/utils/Lock.class.php:19\nStack trace:\n#0 /var/www/html/inc/utils/LockUtils.class.php(17): Lock->__construct('/var/www/html/i...')\n#1 /var/www/html/inc/defines/log.php(14): LockUtils::get('log.lock')\n#2 
/var/www/html/inc/api/APIRegisterAgent.class.php(35): DServerLog::log(20, 'Registered new ...', Array)\n#3 /var/www/html/api/server.php(141): APIRegisterAgent->execute(Array)\n#4 {main}\n  thrown in /var/ww
w/html/inc/utils/Lock.class.php on line 19
[Thu Apr 02 09:37:25.092330 2020] [php7:warn] [pid 36] [client xxx] PHP Warning:  fopen(/var/www/html/inc/utils/locks/log.lock): failed to open stream: Permission denied in /var/www/html/inc/
utils/Lock.class.php on line 17
[Thu Apr 02 09:37:25.092375 2020] [php7:error] [pid 36] [client xxx] PHP Fatal error:  Uncaught Exception: Could not open lockfile '/var/www/html/inc/utils/locks/log.lock'! in /var/www/html/i
nc/utils/Lock.class.php:19\nStack trace:\n#0 /var/www/html/inc/utils/LockUtils.class.php(17): Lock->__construct('/var/www/html/i...')\n#1 /var/www/html/inc/defines/log.php(14): LockUtils::get('log.lock')\n#
2 /var/www/html/inc/api/APIRegisterAgent.class.php(35): DServerLog::log(20, 'Registered new ...', Array)\n#3 /var/www/html/api/server.php(141): APIRegisterAgent->execute(Array)\n#4 {main}\n  thrown in /var/
www/html/inc/utils/Lock.class.php on line 19
[Thu Apr 02 09:43:00.586066 2020] [php7:warn] [pid 32] [client xx] PHP Warning:  fopen(/var/www/html/inc/utils/locks/log.lock): failed to open stream: Permission denied in /var/www/html/inc/
utils/Lock.class.php on line 17
[Thu Apr 02 09:43:00.586116 2020] [php7:error] [pid 32] [client xx] PHP Fatal error:  Uncaught Exception: Could not open lockfile '/var/www/html/inc/utils/locks/log.lock'! in /var/www/html/i
nc/utils/Lock.class.php:19\nStack trace:\n#0 /var/www/html/inc/utils/LockUtils.class.php(17): Lock->__construct('/var/www/html/i...')\n#1 /var/www/html/inc/defines/log.php(14): LockUtils::get('log.lock')\n#
2 /var/www/html/inc/api/APIRegisterAgent.class.php(35): DServerLog::log(20, 'Registered new ...', Array)\n#3 /var/www/html/api/server.php(141): APIRegisterAgent->execute(Array)\n#4 {main}\n  thrown in /var/
www/html/inc/utils/Lock.class.php on line 19
[Thu Apr 02 09:44:15.151294 2020] [php7:warn] [pid 35] [client xx] PHP Warning:  fopen(/var/www/html/inc/utils/locks/log.lock): failed to open stream: Permission denied in /var/www/html/inc/
utils/Lock.class.php on line 17
[Thu Apr 02 09:44:15.151332 2020] [php7:error] [pid 35] [client xxx] PHP Fatal error:  Uncaught Exception: Could not open lockfile '/var/www/html/inc/utils/locks/log.lock'! in /var/www/html/i
nc/utils/Lock.class.php:19\nStack trace:\n#0 /var/www/html/inc/utils/LockUtils.class.php(17): Lock->__construct('/var/www/html/i...')\n#1 /var/www/html/inc/defines/log.php(14): LockUtils::get('log.lock')\n#
2 /var/www/html/inc/api/APIRegisterAgent.class.php(35): DServerLog::log(20, 'Registered new ...', Array)\n#3 /var/www/html/api/server.php(141): APIRegisterAgent->execute(Array)\n#4 {main}\n  thrown in /var/
www/html/inc/utils/Lock.class.php on line 19
[Thu Apr 02 09:45:18.119730 2020] [php7:warn] [pid 25] [client xx] PHP Warning:  fopen(/var/www/html/inc/utils/locks/log.lock): failed to open stream: Permission denied in /var/www/html/inc/
utils/Lock.class.php on line 17
[Thu Apr 02 09:45:18.119767 2020] [php7:error] [pid 25] [client xx] PHP Fatal error:  Uncaught Exception: Could not open lockfile '/var/www/html/inc/utils/locks/log.lock'! in /var/www/html/i
nc/utils/Lock.class.php:19\nStack trace:\n#0 /var/www/html/inc/utils/LockUtils.class.php(17): Lock->__construct('/var/www/html/i...')\n#1 /var/www/html/inc/defines/log.php(14): LockUtils::get('log.lock')\n#
2 /var/www/html/inc/api/APIRegisterAgent.class.php(35): DServerLog::log(20, 'Registered new ...', Array)\n#3 /var/www/html/api/server.php(141): APIRegisterAgent->execute(Array)\n#4 {main}\n  thrown in /var/
www/html/inc/utils/Lock.class.php on line 19

```

note: edited out ip numbers

Above error is related to /var/www/html/inc having incorrect permissions.
```
root@c7c09dc6570b:/var/www/html/inc# ls -la
total 148
drwxr-xr-x 1 www-data www-data   660 Apr  2 09:29 .
drwxr-xr-x 1 www-data www-data   890 Apr  2 09:29 ..
-rwxr-xr-x 1 root     root        10 Apr  2 09:28 .gitignore
-rw-r--r-- 1 root     root     12376 Apr  2 09:28 Auth_Yubico.class.php
-rw-r--r-- 1 root     root       983 Apr  2 09:28 CSRF.class.php
-rwxr-xr-x 1 root     root       622 Apr  2 09:28 Dataset.class.php
-rwxr-xr-x 1 root     root      3554 Apr  2 09:28 Encryption.class.php
-rw-r--r-- 1 root     root        59 Apr  2 09:28 HTException.class.php
-rw-r--r-- 1 root     root       318 Apr  2 09:28 HTMessages.class.php
-rwxr-xr-x 1 root     root      4348 Apr  2 09:28 Lang.class.php
-rwxr-xr-x 1 root     root      6702 Apr  2 09:28 Login.class.php
-rwxr-xr-x 1 root     root      1402 Apr  2 09:28 Menu.class.php
-rw-r--r-- 1 root     root       620 Apr  2 09:28 SConfig.class.php
-rw-r--r-- 1 root     root      1593 Apr  2 09:28 UI.class.php
-rwxr-xr-x 1 root     root     45518 Apr  2 09:28 Util.class.php
drwxr-xr-x 1 root     root       996 Apr  2 09:28 api
-rw-r--r-- 1 root     root       472 Apr  2 09:29 conf.php
-rw-r--r-- 1 root     root       347 Apr  2 09:28 conf.template.php
drwxr-xr-x 1 root     root       472 Apr  2 09:28 defines
drwxr-xr-x 1 root     root      1014 Apr  2 09:28 handlers
-rw-r--r-- 1 root     root       168 Apr  2 09:28 info.php
-rwxr-xr-x 1 root     root      3814 Apr  2 09:28 load.php
-rw-r--r-- 1 root     root       202 Apr  2 09:28 mask.php
drwxr-xr-x 1 root     root       386 Apr  2 09:28 notifications
-rw-r--r-- 1 root     root     11538 Apr  2 09:28 protocol.php
drwxr-xr-x 1 root     root        44 Apr  2 09:28 runner
drwxr-xr-x 1 root     root        74 Apr  2 09:28 templating
drwxr-xr-x 1 root     root       698 Apr  2 09:28 user-api
drwxr-xr-x 1 root     root      1158 Apr  2 09:28 utils

```
chown -R www-data.www-data on the above folder fixes the problem and the client can be registered

**Comment by kpeiruza** [comment]
Ok, I hope it's fixed right now. The folder containing the locks was missing. Docker hub is building the new image right now (docker pull again, please).

If you're using external volumes, ensure that "locks" volume is can be written by Apache.
Check the docker-compose, it will create a volume named "locks", binded into /var/www/html/inc/utils/locks/

If you get the same fopen apache error log, then the volume needs some permission adjustments.

Check the volume names (docker volume ls | grep locks) and attach it to a volume to perform a chmod:

docker run -ti -v NameOfYourLocksVolume:/data debian /bin/bash
 \# chmod 1777 /data/
or even better: 
 \# chown www-data: /data

Enjoy!
